language: node_js
node_js:
  - "0.12"
env:
  - NODE_ENV=TEST
services:
  - mongodb
before_install:
  - npm i -g bower
  - npm i -g istanbul
install:
  - npm install /m
script: "npm run-script test-travis"
