language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
env:
  - NODE_ENV=TEST
services:
  - mongodb
before_install:
  - npm i -g bower
	- sudo apt-get update -qq
  - sudo apt-get install -qq
install:
  - npm install
